name: bookplus-cart
#trigger branch
on:
  push:
    branches:
      - main

permissions:
  id-token: write #Require write permission to Fetch an OIDC token.
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
      # step 2: login into azure using powershell
      - name: Login via Az module
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true
      # step 3: docker login
      - name: docker login
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Connect-AzContainerRegistry -Name datahexrepository
      # set short sha
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      # step 4: docker build and push
      - name: docker build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/bookplus-cart:latest, ${{ secrets.AZURE_CONTAINER_REGISTRY }}/bookplus-cart:${{ steps.vars.outputs.sha_short }}
      # step 5: depolyment
      - name: Trigger deployment endpoint
        run: |
          curl -X POST http://20.235.203.243/ -H "Content-Type: application/json" -d '{"dir": "bookplus-cart"}'